In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print("NumPy Version:", np.__version__)
print("NumPy Installed Successfully!")

NumPy Version: 2.3.4
NumPy Installed Successfully!


## Creating NumPy Arrays

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Type:", type(arr))

Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>


In [5]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


## Indexing in NumPy

Indexing is used to access specific elements from a NumPy array. Just like Python lists, indexing starts from 0.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print("First Element:", arr[0])
print("Third Element:", arr[2])
print("Last Element:", arr[-1])

First Element: 10
Third Element: 30
Last Element: 50


In [7]:
arr2 = np.array([[10, 20],
                 [30, 40]])

print("Element at Row 1 Column 2:", arr2[0][1])
print("Element at Row 2 Column 1:", arr2[1][0])

Element at Row 1 Column 2: 20
Element at Row 2 Column 1: 30


## Reshaping Arrays

Reshape is used to change the shape (dimensions) of an array without changing its data.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(new_arr)

Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array([10,20,30,40,50,60])

new_arr = arr.reshape(3,2)

print(new_arr)

[[10 20]
 [30 40]
 [50 60]]


In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Mathematical Operations and Broadcasting

NumPy allows us to perform mathematical operations directly on arrays without using loops. Broadcasting automatically applies operations to every element of an array.

In [11]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


### Broadcasting

In [12]:
arr = np.array([10, 20, 30, 40])

print("Original Array:", arr)
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)
print("Subtract 10:", arr - 10)

Original Array: [10 20 30 40]
Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Subtract 10: [ 0 10 20 30]


In [13]:
numbers = np.array([5, 10, 15, 20])

print(numbers + 100)
print(numbers * 3)

[105 110 115 120]
[15 30 45 60]


## Statistical Functions

NumPy provides built-in statistical functions such as mean, maximum, minimum, sum and standard deviation. These functions make data analysis fast and easy.

In [14]:
import numpy as np

marks = np.array([78, 65, 89, 92, 55, 70, 81])

print("Marks:", marks)
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Sum:", np.sum(marks))
print("Standard Deviation:", np.std(marks))

Marks: [78 65 89 92 55 70 81]
Mean: 75.71428571428571
Maximum: 92
Minimum: 55
Sum: 530
Standard Deviation: 12.255777479729838


In [15]:
numbers = np.array([12, 25, 18, 30, 45])

print("Average:", np.mean(numbers))
print("Highest:", np.max(numbers))
print("Lowest:", np.min(numbers))
print("Total:", np.sum(numbers))

Average: 26.0
Highest: 45
Lowest: 12
Total: 130


## Random Numbers

In [16]:
import numpy as np

random_numbers = np.random.randint(1, 100, 10)

print("Random Integers:")
print(random_numbers)

Random Integers:
[31  8 54 27 71 71 37 63 22  3]


In [17]:
random_decimal = np.random.rand(5)

print("Random Decimal Numbers:")
print(random_decimal)

Random Decimal Numbers:
[0.41709887 0.24282462 0.95764157 0.56011635 0.11269435]


In [18]:
marks = np.random.randint(35, 101, 20)

print("Student Marks:")
print(marks)

Student Marks:
[ 67  39  73  70  61  95 100  53  89  93  95  82  84  38  64  98  61  90
  42  58]


## NumPy Practice Exercises (1–20)

In [19]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [20]:
print("Data Type:", arr.dtype)

Data Type: int64


In [21]:
print("Shape:", arr.shape)

Shape: (5,)


In [22]:
print("Size:", arr.size)

Size: 5


In [23]:
print("Dimensions:", arr.ndim)

Dimensions: 1


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [25]:
zeros = np.zeros((3,3))

print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
ones = np.ones((2,2))

print(ones)

[[1. 1.]
 [1. 1.]]


In [27]:
numbers = np.arange(1,11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
values = np.linspace(0,10,5)

print(values)

[ 0.   2.5  5.   7.5 10. ]


In [29]:
arr = np.array([10, 25, 40, 15, 30])

print("Maximum Value:", np.max(arr))

Maximum Value: 40


In [30]:
print("Minimum Value:", np.min(arr))

Minimum Value: 10


In [31]:
print("Mean:", np.mean(arr))

Mean: 24.0


In [32]:
print("Sum:", np.sum(arr))

Sum: 120


In [33]:
print("Square Root:")
print(np.sqrt(arr))

Square Root:
[3.16227766 5.         6.32455532 3.87298335 5.47722558]


In [34]:
arr = np.array([1, 2, 3, 4, 5])

print(arr + 10)

[11 12 13 14 15]


In [35]:
print(arr * 5)

[ 5 10 15 20 25]


In [36]:
random_numbers = np.random.randint(1, 100, 5)

print(random_numbers)

[54 67 79 74 38]


In [37]:
random_decimal = np.random.rand(3)

print(random_decimal)

[0.64268992 0.36276717 0.17061174]


In [38]:
numbers = np.array([8, 3, 9, 1, 6])

print("Original Array:", numbers)

print("Sorted Array:", np.sort(numbers))

Original Array: [8 3 9 1 6]
Sorted Array: [1 3 6 8 9]
